name: CI

on:
  pull_request:
    paths-ignore:
      - '**.md'
  release:
    types:
      - published
      - edited

jobs:
  ci-test:
    name: CI-Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          lfs: true
      - name: Run npm
        run: npm ci
      - name: Danger
        run: yarn danger ci --dangerfile tools/danger/dangerfile.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: '*'
      - name: Run Eslint
        run: npm run lint
      - name: Check code style
        run: npm run format
      - name: Run typecheck
        run: npm run lint:ts
      - name: Run unit test
        run: npm run test -- --coverage
      - name: Report test coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          file: ./coverage/**/*
          flags: unittests
      - name: Run Esbuild
        run: BASE_URL=genshin-helper npm run build
      - name: Run Storybook build
        run: npm run build-storybook
      - name: Add 404 fallback to github page
        if: github.ref == 'refs/heads/master'
        run: cp -f dist/index.html dist/404.html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: github.ref == 'refs/heads/master'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
          SINGLE_COMMIT: true
